//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotSpatial.Symbology.Forms.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color ColorButtonColor {
            get {
                return ((global::System.Drawing.Color)(this["ColorButtonColor"]));
            }
            set {
                this["ColorButtonColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ColorButtonCustomColors {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ColorButtonCustomColors"]));
            }
            set {
                this["ColorButtonCustomColors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DetailedPointSymbolControlFontFamilyName {
            get {
                return ((string)(this["DetailedPointSymbolControlFontFamilyName"]));
            }
            set {
                this["DetailedPointSymbolControlFontFamilyName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double DetailedPointSymbolControlSymbolWidth {
            get {
                return ((double)(this["DetailedPointSymbolControlSymbolWidth"]));
            }
            set {
                this["DetailedPointSymbolControlSymbolWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double DetailedPointSymbolControlSymbolHeight {
            get {
                return ((double)(this["DetailedPointSymbolControlSymbolHeight"]));
            }
            set {
                this["DetailedPointSymbolControlSymbolHeight"] = value;
            }
        }
    }
}
